In [2]:
import numpy as np
# import unitest

In [6]:
ar = np.array([[1,2,3], [4,5,6], [7,8,9]])
for row in ar:
    print(str(row))

[1 2 3]
[4 5 6]
[7 8 9]


In [14]:
np.concatenate((ar, [[0,0,0]]), axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 0, 0]])

In [15]:
np.ones((1,2))

array([[1., 1.]])

In [21]:
num_inputs_nodes = 2
num_neurons = 2

weights_no_bias = np.random.randn(num_inputs_nodes, num_neurons)
bias = np.ones((1, num_neurons))
weights = np.concatenate((weights_no_bias, bias), axis=0)

In [22]:
weights

array([[ 0.78357197,  1.71149265],
       [ 1.16542294, -1.09708819],
       [ 1.        ,  1.        ]])

In [12]:
np.array([[5,6]]).shape

(1, 2)

In [13]:
np.array([[1,2],[3,5]]).shape

(2, 2)

In [10]:
np.concatenate?

In [7]:
class Perception:
    
    def __init__(self, num_inputs):
        self.num_inputs = num_inputs
        self.weights = np.random.randn(num_inputs)
        
    def train(self, )

In [13]:
np.random.rand(2,2).size?

Object `size` not found.


In [19]:
np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [24]:
np.concatenate((np.zeros((4,2)), np.ones((4,1))), axis=1)

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [ ]:
np.random.rand(2,2).size

In [8]:
np.random.randint?